// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/cvCraft/ent/education"
	"github.com/ntiGideon/cvCraft/ent/predicate"
	"github.com/ntiGideon/cvCraft/ent/resume"
)

// EducationUpdate is the builder for updating Education entities.
type EducationUpdate struct {
	config
	hooks    []Hook
	mutation *EducationMutation
}

// Where appends a list predicates to the EducationUpdate builder.
func (eu *EducationUpdate) Where(ps ...predicate.Education) *EducationUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetInstitution sets the "institution" field.
func (eu *EducationUpdate) SetInstitution(s string) *EducationUpdate {
	eu.mutation.SetInstitution(s)
	return eu
}

// SetNillableInstitution sets the "institution" field if the given value is not nil.
func (eu *EducationUpdate) SetNillableInstitution(s *string) *EducationUpdate {
	if s != nil {
		eu.SetInstitution(*s)
	}
	return eu
}

// SetDegree sets the "degree" field.
func (eu *EducationUpdate) SetDegree(s string) *EducationUpdate {
	eu.mutation.SetDegree(s)
	return eu
}

// SetNillableDegree sets the "degree" field if the given value is not nil.
func (eu *EducationUpdate) SetNillableDegree(s *string) *EducationUpdate {
	if s != nil {
		eu.SetDegree(*s)
	}
	return eu
}

// SetField sets the "field" field.
func (eu *EducationUpdate) SetField(s string) *EducationUpdate {
	eu.mutation.SetFieldField(s)
	return eu
}

// SetNillableField sets the "field" field if the given value is not nil.
func (eu *EducationUpdate) SetNillableField(s *string) *EducationUpdate {
	if s != nil {
		eu.SetField(*s)
	}
	return eu
}

// SetStartDate sets the "start_date" field.
func (eu *EducationUpdate) SetStartDate(t time.Time) *EducationUpdate {
	eu.mutation.SetStartDate(t)
	return eu
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (eu *EducationUpdate) SetNillableStartDate(t *time.Time) *EducationUpdate {
	if t != nil {
		eu.SetStartDate(*t)
	}
	return eu
}

// SetEndDate sets the "end_date" field.
func (eu *EducationUpdate) SetEndDate(t time.Time) *EducationUpdate {
	eu.mutation.SetEndDate(t)
	return eu
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (eu *EducationUpdate) SetNillableEndDate(t *time.Time) *EducationUpdate {
	if t != nil {
		eu.SetEndDate(*t)
	}
	return eu
}

// ClearEndDate clears the value of the "end_date" field.
func (eu *EducationUpdate) ClearEndDate() *EducationUpdate {
	eu.mutation.ClearEndDate()
	return eu
}

// SetDescription sets the "description" field.
func (eu *EducationUpdate) SetDescription(s string) *EducationUpdate {
	eu.mutation.SetDescription(s)
	return eu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (eu *EducationUpdate) SetNillableDescription(s *string) *EducationUpdate {
	if s != nil {
		eu.SetDescription(*s)
	}
	return eu
}

// ClearDescription clears the value of the "description" field.
func (eu *EducationUpdate) ClearDescription() *EducationUpdate {
	eu.mutation.ClearDescription()
	return eu
}

// SetGrade sets the "grade" field.
func (eu *EducationUpdate) SetGrade(s string) *EducationUpdate {
	eu.mutation.SetGrade(s)
	return eu
}

// SetNillableGrade sets the "grade" field if the given value is not nil.
func (eu *EducationUpdate) SetNillableGrade(s *string) *EducationUpdate {
	if s != nil {
		eu.SetGrade(*s)
	}
	return eu
}

// ClearGrade clears the value of the "grade" field.
func (eu *EducationUpdate) ClearGrade() *EducationUpdate {
	eu.mutation.ClearGrade()
	return eu
}

// AddResumeIDs adds the "resume" edge to the Resume entity by IDs.
func (eu *EducationUpdate) AddResumeIDs(ids ...int) *EducationUpdate {
	eu.mutation.AddResumeIDs(ids...)
	return eu
}

// AddResume adds the "resume" edges to the Resume entity.
func (eu *EducationUpdate) AddResume(r ...*Resume) *EducationUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return eu.AddResumeIDs(ids...)
}

// Mutation returns the EducationMutation object of the builder.
func (eu *EducationUpdate) Mutation() *EducationMutation {
	return eu.mutation
}

// ClearResume clears all "resume" edges to the Resume entity.
func (eu *EducationUpdate) ClearResume() *EducationUpdate {
	eu.mutation.ClearResume()
	return eu
}

// RemoveResumeIDs removes the "resume" edge to Resume entities by IDs.
func (eu *EducationUpdate) RemoveResumeIDs(ids ...int) *EducationUpdate {
	eu.mutation.RemoveResumeIDs(ids...)
	return eu
}

// RemoveResume removes "resume" edges to Resume entities.
func (eu *EducationUpdate) RemoveResume(r ...*Resume) *EducationUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return eu.RemoveResumeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EducationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EducationUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EducationUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EducationUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EducationUpdate) check() error {
	if v, ok := eu.mutation.Institution(); ok {
		if err := education.InstitutionValidator(v); err != nil {
			return &ValidationError{Name: "institution", err: fmt.Errorf(`ent: validator failed for field "Education.institution": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Degree(); ok {
		if err := education.DegreeValidator(v); err != nil {
			return &ValidationError{Name: "degree", err: fmt.Errorf(`ent: validator failed for field "Education.degree": %w`, err)}
		}
	}
	if v, ok := eu.mutation.GetField(); ok {
		if err := education.FieldValidator(v); err != nil {
			return &ValidationError{Name: "field", err: fmt.Errorf(`ent: validator failed for field "Education.field": %w`, err)}
		}
	}
	return nil
}

func (eu *EducationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(education.Table, education.Columns, sqlgraph.NewFieldSpec(education.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Institution(); ok {
		_spec.SetField(education.FieldInstitution, field.TypeString, value)
	}
	if value, ok := eu.mutation.Degree(); ok {
		_spec.SetField(education.FieldDegree, field.TypeString, value)
	}
	if value, ok := eu.mutation.GetField(); ok {
		_spec.SetField(education.FieldField, field.TypeString, value)
	}
	if value, ok := eu.mutation.StartDate(); ok {
		_spec.SetField(education.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := eu.mutation.EndDate(); ok {
		_spec.SetField(education.FieldEndDate, field.TypeTime, value)
	}
	if eu.mutation.EndDateCleared() {
		_spec.ClearField(education.FieldEndDate, field.TypeTime)
	}
	if value, ok := eu.mutation.Description(); ok {
		_spec.SetField(education.FieldDescription, field.TypeString, value)
	}
	if eu.mutation.DescriptionCleared() {
		_spec.ClearField(education.FieldDescription, field.TypeString)
	}
	if value, ok := eu.mutation.Grade(); ok {
		_spec.SetField(education.FieldGrade, field.TypeString, value)
	}
	if eu.mutation.GradeCleared() {
		_spec.ClearField(education.FieldGrade, field.TypeString)
	}
	if eu.mutation.ResumeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   education.ResumeTable,
			Columns: education.ResumePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.RemovedResumeIDs(); len(nodes) > 0 && !eu.mutation.ResumeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   education.ResumeTable,
			Columns: education.ResumePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.ResumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   education.ResumeTable,
			Columns: education.ResumePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{education.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EducationUpdateOne is the builder for updating a single Education entity.
type EducationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EducationMutation
}

// SetInstitution sets the "institution" field.
func (euo *EducationUpdateOne) SetInstitution(s string) *EducationUpdateOne {
	euo.mutation.SetInstitution(s)
	return euo
}

// SetNillableInstitution sets the "institution" field if the given value is not nil.
func (euo *EducationUpdateOne) SetNillableInstitution(s *string) *EducationUpdateOne {
	if s != nil {
		euo.SetInstitution(*s)
	}
	return euo
}

// SetDegree sets the "degree" field.
func (euo *EducationUpdateOne) SetDegree(s string) *EducationUpdateOne {
	euo.mutation.SetDegree(s)
	return euo
}

// SetNillableDegree sets the "degree" field if the given value is not nil.
func (euo *EducationUpdateOne) SetNillableDegree(s *string) *EducationUpdateOne {
	if s != nil {
		euo.SetDegree(*s)
	}
	return euo
}

// SetField sets the "field" field.
func (euo *EducationUpdateOne) SetField(s string) *EducationUpdateOne {
	euo.mutation.SetFieldField(s)
	return euo
}

// SetNillableField sets the "field" field if the given value is not nil.
func (euo *EducationUpdateOne) SetNillableField(s *string) *EducationUpdateOne {
	if s != nil {
		euo.SetField(*s)
	}
	return euo
}

// SetStartDate sets the "start_date" field.
func (euo *EducationUpdateOne) SetStartDate(t time.Time) *EducationUpdateOne {
	euo.mutation.SetStartDate(t)
	return euo
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (euo *EducationUpdateOne) SetNillableStartDate(t *time.Time) *EducationUpdateOne {
	if t != nil {
		euo.SetStartDate(*t)
	}
	return euo
}

// SetEndDate sets the "end_date" field.
func (euo *EducationUpdateOne) SetEndDate(t time.Time) *EducationUpdateOne {
	euo.mutation.SetEndDate(t)
	return euo
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (euo *EducationUpdateOne) SetNillableEndDate(t *time.Time) *EducationUpdateOne {
	if t != nil {
		euo.SetEndDate(*t)
	}
	return euo
}

// ClearEndDate clears the value of the "end_date" field.
func (euo *EducationUpdateOne) ClearEndDate() *EducationUpdateOne {
	euo.mutation.ClearEndDate()
	return euo
}

// SetDescription sets the "description" field.
func (euo *EducationUpdateOne) SetDescription(s string) *EducationUpdateOne {
	euo.mutation.SetDescription(s)
	return euo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (euo *EducationUpdateOne) SetNillableDescription(s *string) *EducationUpdateOne {
	if s != nil {
		euo.SetDescription(*s)
	}
	return euo
}

// ClearDescription clears the value of the "description" field.
func (euo *EducationUpdateOne) ClearDescription() *EducationUpdateOne {
	euo.mutation.ClearDescription()
	return euo
}

// SetGrade sets the "grade" field.
func (euo *EducationUpdateOne) SetGrade(s string) *EducationUpdateOne {
	euo.mutation.SetGrade(s)
	return euo
}

// SetNillableGrade sets the "grade" field if the given value is not nil.
func (euo *EducationUpdateOne) SetNillableGrade(s *string) *EducationUpdateOne {
	if s != nil {
		euo.SetGrade(*s)
	}
	return euo
}

// ClearGrade clears the value of the "grade" field.
func (euo *EducationUpdateOne) ClearGrade() *EducationUpdateOne {
	euo.mutation.ClearGrade()
	return euo
}

// AddResumeIDs adds the "resume" edge to the Resume entity by IDs.
func (euo *EducationUpdateOne) AddResumeIDs(ids ...int) *EducationUpdateOne {
	euo.mutation.AddResumeIDs(ids...)
	return euo
}

// AddResume adds the "resume" edges to the Resume entity.
func (euo *EducationUpdateOne) AddResume(r ...*Resume) *EducationUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return euo.AddResumeIDs(ids...)
}

// Mutation returns the EducationMutation object of the builder.
func (euo *EducationUpdateOne) Mutation() *EducationMutation {
	return euo.mutation
}

// ClearResume clears all "resume" edges to the Resume entity.
func (euo *EducationUpdateOne) ClearResume() *EducationUpdateOne {
	euo.mutation.ClearResume()
	return euo
}

// RemoveResumeIDs removes the "resume" edge to Resume entities by IDs.
func (euo *EducationUpdateOne) RemoveResumeIDs(ids ...int) *EducationUpdateOne {
	euo.mutation.RemoveResumeIDs(ids...)
	return euo
}

// RemoveResume removes "resume" edges to Resume entities.
func (euo *EducationUpdateOne) RemoveResume(r ...*Resume) *EducationUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return euo.RemoveResumeIDs(ids...)
}

// Where appends a list predicates to the EducationUpdate builder.
func (euo *EducationUpdateOne) Where(ps ...predicate.Education) *EducationUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EducationUpdateOne) Select(field string, fields ...string) *EducationUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Education entity.
func (euo *EducationUpdateOne) Save(ctx context.Context) (*Education, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EducationUpdateOne) SaveX(ctx context.Context) *Education {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EducationUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EducationUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EducationUpdateOne) check() error {
	if v, ok := euo.mutation.Institution(); ok {
		if err := education.InstitutionValidator(v); err != nil {
			return &ValidationError{Name: "institution", err: fmt.Errorf(`ent: validator failed for field "Education.institution": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Degree(); ok {
		if err := education.DegreeValidator(v); err != nil {
			return &ValidationError{Name: "degree", err: fmt.Errorf(`ent: validator failed for field "Education.degree": %w`, err)}
		}
	}
	if v, ok := euo.mutation.GetField(); ok {
		if err := education.FieldValidator(v); err != nil {
			return &ValidationError{Name: "field", err: fmt.Errorf(`ent: validator failed for field "Education.field": %w`, err)}
		}
	}
	return nil
}

func (euo *EducationUpdateOne) sqlSave(ctx context.Context) (_node *Education, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(education.Table, education.Columns, sqlgraph.NewFieldSpec(education.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Education.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, education.FieldID)
		for _, f := range fields {
			if !education.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != education.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.Institution(); ok {
		_spec.SetField(education.FieldInstitution, field.TypeString, value)
	}
	if value, ok := euo.mutation.Degree(); ok {
		_spec.SetField(education.FieldDegree, field.TypeString, value)
	}
	if value, ok := euo.mutation.GetField(); ok {
		_spec.SetField(education.FieldField, field.TypeString, value)
	}
	if value, ok := euo.mutation.StartDate(); ok {
		_spec.SetField(education.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := euo.mutation.EndDate(); ok {
		_spec.SetField(education.FieldEndDate, field.TypeTime, value)
	}
	if euo.mutation.EndDateCleared() {
		_spec.ClearField(education.FieldEndDate, field.TypeTime)
	}
	if value, ok := euo.mutation.Description(); ok {
		_spec.SetField(education.FieldDescription, field.TypeString, value)
	}
	if euo.mutation.DescriptionCleared() {
		_spec.ClearField(education.FieldDescription, field.TypeString)
	}
	if value, ok := euo.mutation.Grade(); ok {
		_spec.SetField(education.FieldGrade, field.TypeString, value)
	}
	if euo.mutation.GradeCleared() {
		_spec.ClearField(education.FieldGrade, field.TypeString)
	}
	if euo.mutation.ResumeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   education.ResumeTable,
			Columns: education.ResumePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.RemovedResumeIDs(); len(nodes) > 0 && !euo.mutation.ResumeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   education.ResumeTable,
			Columns: education.ResumePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.ResumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   education.ResumeTable,
			Columns: education.ResumePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Education{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{education.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
