// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/cvCraft/ent/certification"
	"github.com/ntiGideon/cvCraft/ent/education"
	"github.com/ntiGideon/cvCraft/ent/experience"
	"github.com/ntiGideon/cvCraft/ent/personalinfo"
	"github.com/ntiGideon/cvCraft/ent/predicate"
	"github.com/ntiGideon/cvCraft/ent/project"
	"github.com/ntiGideon/cvCraft/ent/resume"
	"github.com/ntiGideon/cvCraft/ent/skill"
	"github.com/ntiGideon/cvCraft/ent/template"
	"github.com/ntiGideon/cvCraft/ent/user"
)

// ResumeQuery is the builder for querying Resume entities.
type ResumeQuery struct {
	config
	ctx                *QueryContext
	order              []resume.OrderOption
	inters             []Interceptor
	predicates         []predicate.Resume
	withOwner          *UserQuery
	withTemplate       *TemplateQuery
	withPersonalInfo   *PersonalInfoQuery
	withExperiences    *ExperienceQuery
	withEducations     *EducationQuery
	withSkills         *SkillQuery
	withProjects       *ProjectQuery
	withCertifications *CertificationQuery
	withFKs            bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResumeQuery builder.
func (rq *ResumeQuery) Where(ps ...predicate.Resume) *ResumeQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *ResumeQuery) Limit(limit int) *ResumeQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *ResumeQuery) Offset(offset int) *ResumeQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *ResumeQuery) Unique(unique bool) *ResumeQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *ResumeQuery) Order(o ...resume.OrderOption) *ResumeQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryOwner chains the current query on the "owner" edge.
func (rq *ResumeQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resume.Table, resume.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, resume.OwnerTable, resume.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTemplate chains the current query on the "template" edge.
func (rq *ResumeQuery) QueryTemplate() *TemplateQuery {
	query := (&TemplateClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resume.Table, resume.FieldID, selector),
			sqlgraph.To(template.Table, template.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, resume.TemplateTable, resume.TemplateColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPersonalInfo chains the current query on the "personal_info" edge.
func (rq *ResumeQuery) QueryPersonalInfo() *PersonalInfoQuery {
	query := (&PersonalInfoClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resume.Table, resume.FieldID, selector),
			sqlgraph.To(personalinfo.Table, personalinfo.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, resume.PersonalInfoTable, resume.PersonalInfoColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExperiences chains the current query on the "experiences" edge.
func (rq *ResumeQuery) QueryExperiences() *ExperienceQuery {
	query := (&ExperienceClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resume.Table, resume.FieldID, selector),
			sqlgraph.To(experience.Table, experience.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, resume.ExperiencesTable, resume.ExperiencesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEducations chains the current query on the "educations" edge.
func (rq *ResumeQuery) QueryEducations() *EducationQuery {
	query := (&EducationClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resume.Table, resume.FieldID, selector),
			sqlgraph.To(education.Table, education.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, resume.EducationsTable, resume.EducationsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySkills chains the current query on the "skills" edge.
func (rq *ResumeQuery) QuerySkills() *SkillQuery {
	query := (&SkillClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resume.Table, resume.FieldID, selector),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, resume.SkillsTable, resume.SkillsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProjects chains the current query on the "projects" edge.
func (rq *ResumeQuery) QueryProjects() *ProjectQuery {
	query := (&ProjectClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resume.Table, resume.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, resume.ProjectsTable, resume.ProjectsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCertifications chains the current query on the "certifications" edge.
func (rq *ResumeQuery) QueryCertifications() *CertificationQuery {
	query := (&CertificationClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resume.Table, resume.FieldID, selector),
			sqlgraph.To(certification.Table, certification.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, resume.CertificationsTable, resume.CertificationsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Resume entity from the query.
// Returns a *NotFoundError when no Resume was found.
func (rq *ResumeQuery) First(ctx context.Context) (*Resume, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{resume.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *ResumeQuery) FirstX(ctx context.Context) *Resume {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Resume ID from the query.
// Returns a *NotFoundError when no Resume ID was found.
func (rq *ResumeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{resume.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *ResumeQuery) FirstIDX(ctx context.Context) int {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Resume entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Resume entity is found.
// Returns a *NotFoundError when no Resume entities are found.
func (rq *ResumeQuery) Only(ctx context.Context) (*Resume, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{resume.Label}
	default:
		return nil, &NotSingularError{resume.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *ResumeQuery) OnlyX(ctx context.Context) *Resume {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Resume ID in the query.
// Returns a *NotSingularError when more than one Resume ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *ResumeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{resume.Label}
	default:
		err = &NotSingularError{resume.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *ResumeQuery) OnlyIDX(ctx context.Context) int {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Resumes.
func (rq *ResumeQuery) All(ctx context.Context) ([]*Resume, error) {
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryAll)
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Resume, *ResumeQuery]()
	return withInterceptors[[]*Resume](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *ResumeQuery) AllX(ctx context.Context) []*Resume {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Resume IDs.
func (rq *ResumeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryIDs)
	if err = rq.Select(resume.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *ResumeQuery) IDsX(ctx context.Context) []int {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *ResumeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryCount)
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*ResumeQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *ResumeQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *ResumeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryExist)
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *ResumeQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResumeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *ResumeQuery) Clone() *ResumeQuery {
	if rq == nil {
		return nil
	}
	return &ResumeQuery{
		config:             rq.config,
		ctx:                rq.ctx.Clone(),
		order:              append([]resume.OrderOption{}, rq.order...),
		inters:             append([]Interceptor{}, rq.inters...),
		predicates:         append([]predicate.Resume{}, rq.predicates...),
		withOwner:          rq.withOwner.Clone(),
		withTemplate:       rq.withTemplate.Clone(),
		withPersonalInfo:   rq.withPersonalInfo.Clone(),
		withExperiences:    rq.withExperiences.Clone(),
		withEducations:     rq.withEducations.Clone(),
		withSkills:         rq.withSkills.Clone(),
		withProjects:       rq.withProjects.Clone(),
		withCertifications: rq.withCertifications.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResumeQuery) WithOwner(opts ...func(*UserQuery)) *ResumeQuery {
	query := (&UserClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withOwner = query
	return rq
}

// WithTemplate tells the query-builder to eager-load the nodes that are connected to
// the "template" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResumeQuery) WithTemplate(opts ...func(*TemplateQuery)) *ResumeQuery {
	query := (&TemplateClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withTemplate = query
	return rq
}

// WithPersonalInfo tells the query-builder to eager-load the nodes that are connected to
// the "personal_info" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResumeQuery) WithPersonalInfo(opts ...func(*PersonalInfoQuery)) *ResumeQuery {
	query := (&PersonalInfoClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withPersonalInfo = query
	return rq
}

// WithExperiences tells the query-builder to eager-load the nodes that are connected to
// the "experiences" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResumeQuery) WithExperiences(opts ...func(*ExperienceQuery)) *ResumeQuery {
	query := (&ExperienceClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withExperiences = query
	return rq
}

// WithEducations tells the query-builder to eager-load the nodes that are connected to
// the "educations" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResumeQuery) WithEducations(opts ...func(*EducationQuery)) *ResumeQuery {
	query := (&EducationClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withEducations = query
	return rq
}

// WithSkills tells the query-builder to eager-load the nodes that are connected to
// the "skills" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResumeQuery) WithSkills(opts ...func(*SkillQuery)) *ResumeQuery {
	query := (&SkillClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withSkills = query
	return rq
}

// WithProjects tells the query-builder to eager-load the nodes that are connected to
// the "projects" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResumeQuery) WithProjects(opts ...func(*ProjectQuery)) *ResumeQuery {
	query := (&ProjectClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withProjects = query
	return rq
}

// WithCertifications tells the query-builder to eager-load the nodes that are connected to
// the "certifications" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ResumeQuery) WithCertifications(opts ...func(*CertificationQuery)) *ResumeQuery {
	query := (&CertificationClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withCertifications = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Resume.Query().
//		GroupBy(resume.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *ResumeQuery) GroupBy(field string, fields ...string) *ResumeGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ResumeGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = resume.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Resume.Query().
//		Select(resume.FieldName).
//		Scan(ctx, &v)
func (rq *ResumeQuery) Select(fields ...string) *ResumeSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &ResumeSelect{ResumeQuery: rq}
	sbuild.label = resume.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ResumeSelect configured with the given aggregations.
func (rq *ResumeQuery) Aggregate(fns ...AggregateFunc) *ResumeSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *ResumeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !resume.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *ResumeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Resume, error) {
	var (
		nodes       = []*Resume{}
		withFKs     = rq.withFKs
		_spec       = rq.querySpec()
		loadedTypes = [8]bool{
			rq.withOwner != nil,
			rq.withTemplate != nil,
			rq.withPersonalInfo != nil,
			rq.withExperiences != nil,
			rq.withEducations != nil,
			rq.withSkills != nil,
			rq.withProjects != nil,
			rq.withCertifications != nil,
		}
	)
	if rq.withOwner != nil || rq.withTemplate != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, resume.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Resume).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Resume{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withOwner; query != nil {
		if err := rq.loadOwner(ctx, query, nodes, nil,
			func(n *Resume, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withTemplate; query != nil {
		if err := rq.loadTemplate(ctx, query, nodes, nil,
			func(n *Resume, e *Template) { n.Edges.Template = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withPersonalInfo; query != nil {
		if err := rq.loadPersonalInfo(ctx, query, nodes, nil,
			func(n *Resume, e *PersonalInfo) { n.Edges.PersonalInfo = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withExperiences; query != nil {
		if err := rq.loadExperiences(ctx, query, nodes,
			func(n *Resume) { n.Edges.Experiences = []*Experience{} },
			func(n *Resume, e *Experience) { n.Edges.Experiences = append(n.Edges.Experiences, e) }); err != nil {
			return nil, err
		}
	}
	if query := rq.withEducations; query != nil {
		if err := rq.loadEducations(ctx, query, nodes,
			func(n *Resume) { n.Edges.Educations = []*Education{} },
			func(n *Resume, e *Education) { n.Edges.Educations = append(n.Edges.Educations, e) }); err != nil {
			return nil, err
		}
	}
	if query := rq.withSkills; query != nil {
		if err := rq.loadSkills(ctx, query, nodes,
			func(n *Resume) { n.Edges.Skills = []*Skill{} },
			func(n *Resume, e *Skill) { n.Edges.Skills = append(n.Edges.Skills, e) }); err != nil {
			return nil, err
		}
	}
	if query := rq.withProjects; query != nil {
		if err := rq.loadProjects(ctx, query, nodes,
			func(n *Resume) { n.Edges.Projects = []*Project{} },
			func(n *Resume, e *Project) { n.Edges.Projects = append(n.Edges.Projects, e) }); err != nil {
			return nil, err
		}
	}
	if query := rq.withCertifications; query != nil {
		if err := rq.loadCertifications(ctx, query, nodes,
			func(n *Resume) { n.Edges.Certifications = []*Certification{} },
			func(n *Resume, e *Certification) { n.Edges.Certifications = append(n.Edges.Certifications, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *ResumeQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*Resume, init func(*Resume), assign func(*Resume, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Resume)
	for i := range nodes {
		if nodes[i].user_resumes == nil {
			continue
		}
		fk := *nodes[i].user_resumes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_resumes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rq *ResumeQuery) loadTemplate(ctx context.Context, query *TemplateQuery, nodes []*Resume, init func(*Resume), assign func(*Resume, *Template)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Resume)
	for i := range nodes {
		if nodes[i].template_resumes == nil {
			continue
		}
		fk := *nodes[i].template_resumes
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(template.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "template_resumes" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rq *ResumeQuery) loadPersonalInfo(ctx context.Context, query *PersonalInfoQuery, nodes []*Resume, init func(*Resume), assign func(*Resume, *PersonalInfo)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Resume)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.PersonalInfo(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(resume.PersonalInfoColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.resume_personal_info
		if fk == nil {
			return fmt.Errorf(`foreign-key "resume_personal_info" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "resume_personal_info" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (rq *ResumeQuery) loadExperiences(ctx context.Context, query *ExperienceQuery, nodes []*Resume, init func(*Resume), assign func(*Resume, *Experience)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Resume)
	nids := make(map[int]map[*Resume]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(resume.ExperiencesTable)
		s.Join(joinT).On(s.C(experience.FieldID), joinT.C(resume.ExperiencesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(resume.ExperiencesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(resume.ExperiencesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Resume]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Experience](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "experiences" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (rq *ResumeQuery) loadEducations(ctx context.Context, query *EducationQuery, nodes []*Resume, init func(*Resume), assign func(*Resume, *Education)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Resume)
	nids := make(map[int]map[*Resume]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(resume.EducationsTable)
		s.Join(joinT).On(s.C(education.FieldID), joinT.C(resume.EducationsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(resume.EducationsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(resume.EducationsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Resume]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Education](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "educations" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (rq *ResumeQuery) loadSkills(ctx context.Context, query *SkillQuery, nodes []*Resume, init func(*Resume), assign func(*Resume, *Skill)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Resume)
	nids := make(map[int]map[*Resume]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(resume.SkillsTable)
		s.Join(joinT).On(s.C(skill.FieldID), joinT.C(resume.SkillsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(resume.SkillsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(resume.SkillsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Resume]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Skill](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "skills" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (rq *ResumeQuery) loadProjects(ctx context.Context, query *ProjectQuery, nodes []*Resume, init func(*Resume), assign func(*Resume, *Project)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Resume)
	nids := make(map[int]map[*Resume]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(resume.ProjectsTable)
		s.Join(joinT).On(s.C(project.FieldID), joinT.C(resume.ProjectsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(resume.ProjectsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(resume.ProjectsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Resume]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Project](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "projects" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (rq *ResumeQuery) loadCertifications(ctx context.Context, query *CertificationQuery, nodes []*Resume, init func(*Resume), assign func(*Resume, *Certification)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Resume)
	nids := make(map[int]map[*Resume]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(resume.CertificationsTable)
		s.Join(joinT).On(s.C(certification.FieldID), joinT.C(resume.CertificationsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(resume.CertificationsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(resume.CertificationsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Resume]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Certification](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "certifications" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (rq *ResumeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *ResumeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(resume.Table, resume.Columns, sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resume.FieldID)
		for i := range fields {
			if fields[i] != resume.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *ResumeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(resume.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = resume.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ResumeGroupBy is the group-by builder for Resume entities.
type ResumeGroupBy struct {
	selector
	build *ResumeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *ResumeGroupBy) Aggregate(fns ...AggregateFunc) *ResumeGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *ResumeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, ent.OpQueryGroupBy)
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResumeQuery, *ResumeGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *ResumeGroupBy) sqlScan(ctx context.Context, root *ResumeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ResumeSelect is the builder for selecting fields of Resume entities.
type ResumeSelect struct {
	*ResumeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *ResumeSelect) Aggregate(fns ...AggregateFunc) *ResumeSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *ResumeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, ent.OpQuerySelect)
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResumeQuery, *ResumeSelect](ctx, rs.ResumeQuery, rs, rs.inters, v)
}

func (rs *ResumeSelect) sqlScan(ctx context.Context, root *ResumeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
