// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ntiGideon/cvCraft/ent/certification"
	"github.com/ntiGideon/cvCraft/ent/education"
	"github.com/ntiGideon/cvCraft/ent/experience"
	"github.com/ntiGideon/cvCraft/ent/personalinfo"
	"github.com/ntiGideon/cvCraft/ent/project"
	"github.com/ntiGideon/cvCraft/ent/resume"
	"github.com/ntiGideon/cvCraft/ent/skill"
	"github.com/ntiGideon/cvCraft/ent/template"
	"github.com/ntiGideon/cvCraft/ent/user"
)

// ResumeCreate is the builder for creating a Resume entity.
type ResumeCreate struct {
	config
	mutation *ResumeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (rc *ResumeCreate) SetName(s string) *ResumeCreate {
	rc.mutation.SetName(s)
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *ResumeCreate) SetCreatedAt(t time.Time) *ResumeCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *ResumeCreate) SetNillableCreatedAt(t *time.Time) *ResumeCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *ResumeCreate) SetUpdatedAt(t time.Time) *ResumeCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *ResumeCreate) SetNillableUpdatedAt(t *time.Time) *ResumeCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetShared sets the "shared" field.
func (rc *ResumeCreate) SetShared(b bool) *ResumeCreate {
	rc.mutation.SetShared(b)
	return rc
}

// SetNillableShared sets the "shared" field if the given value is not nil.
func (rc *ResumeCreate) SetNillableShared(b *bool) *ResumeCreate {
	if b != nil {
		rc.SetShared(*b)
	}
	return rc
}

// SetShareCode sets the "share_code" field.
func (rc *ResumeCreate) SetShareCode(s string) *ResumeCreate {
	rc.mutation.SetShareCode(s)
	return rc
}

// SetNillableShareCode sets the "share_code" field if the given value is not nil.
func (rc *ResumeCreate) SetNillableShareCode(s *string) *ResumeCreate {
	if s != nil {
		rc.SetShareCode(*s)
	}
	return rc
}

// SetStatus sets the "status" field.
func (rc *ResumeCreate) SetStatus(r resume.Status) *ResumeCreate {
	rc.mutation.SetStatus(r)
	return rc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rc *ResumeCreate) SetNillableStatus(r *resume.Status) *ResumeCreate {
	if r != nil {
		rc.SetStatus(*r)
	}
	return rc
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (rc *ResumeCreate) SetOwnerID(id int) *ResumeCreate {
	rc.mutation.SetOwnerID(id)
	return rc
}

// SetOwner sets the "owner" edge to the User entity.
func (rc *ResumeCreate) SetOwner(u *User) *ResumeCreate {
	return rc.SetOwnerID(u.ID)
}

// SetTemplateID sets the "template" edge to the Template entity by ID.
func (rc *ResumeCreate) SetTemplateID(id int) *ResumeCreate {
	rc.mutation.SetTemplateID(id)
	return rc
}

// SetNillableTemplateID sets the "template" edge to the Template entity by ID if the given value is not nil.
func (rc *ResumeCreate) SetNillableTemplateID(id *int) *ResumeCreate {
	if id != nil {
		rc = rc.SetTemplateID(*id)
	}
	return rc
}

// SetTemplate sets the "template" edge to the Template entity.
func (rc *ResumeCreate) SetTemplate(t *Template) *ResumeCreate {
	return rc.SetTemplateID(t.ID)
}

// SetPersonalInfoID sets the "personal_info" edge to the PersonalInfo entity by ID.
func (rc *ResumeCreate) SetPersonalInfoID(id int) *ResumeCreate {
	rc.mutation.SetPersonalInfoID(id)
	return rc
}

// SetNillablePersonalInfoID sets the "personal_info" edge to the PersonalInfo entity by ID if the given value is not nil.
func (rc *ResumeCreate) SetNillablePersonalInfoID(id *int) *ResumeCreate {
	if id != nil {
		rc = rc.SetPersonalInfoID(*id)
	}
	return rc
}

// SetPersonalInfo sets the "personal_info" edge to the PersonalInfo entity.
func (rc *ResumeCreate) SetPersonalInfo(p *PersonalInfo) *ResumeCreate {
	return rc.SetPersonalInfoID(p.ID)
}

// AddExperienceIDs adds the "experiences" edge to the Experience entity by IDs.
func (rc *ResumeCreate) AddExperienceIDs(ids ...int) *ResumeCreate {
	rc.mutation.AddExperienceIDs(ids...)
	return rc
}

// AddExperiences adds the "experiences" edges to the Experience entity.
func (rc *ResumeCreate) AddExperiences(e ...*Experience) *ResumeCreate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return rc.AddExperienceIDs(ids...)
}

// AddEducationIDs adds the "educations" edge to the Education entity by IDs.
func (rc *ResumeCreate) AddEducationIDs(ids ...int) *ResumeCreate {
	rc.mutation.AddEducationIDs(ids...)
	return rc
}

// AddEducations adds the "educations" edges to the Education entity.
func (rc *ResumeCreate) AddEducations(e ...*Education) *ResumeCreate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return rc.AddEducationIDs(ids...)
}

// AddSkillIDs adds the "skills" edge to the Skill entity by IDs.
func (rc *ResumeCreate) AddSkillIDs(ids ...int) *ResumeCreate {
	rc.mutation.AddSkillIDs(ids...)
	return rc
}

// AddSkills adds the "skills" edges to the Skill entity.
func (rc *ResumeCreate) AddSkills(s ...*Skill) *ResumeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return rc.AddSkillIDs(ids...)
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (rc *ResumeCreate) AddProjectIDs(ids ...int) *ResumeCreate {
	rc.mutation.AddProjectIDs(ids...)
	return rc
}

// AddProjects adds the "projects" edges to the Project entity.
func (rc *ResumeCreate) AddProjects(p ...*Project) *ResumeCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return rc.AddProjectIDs(ids...)
}

// AddCertificationIDs adds the "certifications" edge to the Certification entity by IDs.
func (rc *ResumeCreate) AddCertificationIDs(ids ...int) *ResumeCreate {
	rc.mutation.AddCertificationIDs(ids...)
	return rc
}

// AddCertifications adds the "certifications" edges to the Certification entity.
func (rc *ResumeCreate) AddCertifications(c ...*Certification) *ResumeCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return rc.AddCertificationIDs(ids...)
}

// Mutation returns the ResumeMutation object of the builder.
func (rc *ResumeCreate) Mutation() *ResumeMutation {
	return rc.mutation
}

// Save creates the Resume in the database.
func (rc *ResumeCreate) Save(ctx context.Context) (*Resume, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ResumeCreate) SaveX(ctx context.Context) *Resume {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ResumeCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ResumeCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *ResumeCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := resume.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := resume.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
	if _, ok := rc.mutation.Shared(); !ok {
		v := resume.DefaultShared
		rc.mutation.SetShared(v)
	}
	if _, ok := rc.mutation.Status(); !ok {
		v := resume.DefaultStatus
		rc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ResumeCreate) check() error {
	if _, ok := rc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Resume.name"`)}
	}
	if v, ok := rc.mutation.Name(); ok {
		if err := resume.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resume.name": %w`, err)}
		}
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Resume.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Resume.updated_at"`)}
	}
	if _, ok := rc.mutation.Shared(); !ok {
		return &ValidationError{Name: "shared", err: errors.New(`ent: missing required field "Resume.shared"`)}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Resume.status"`)}
	}
	if v, ok := rc.mutation.Status(); ok {
		if err := resume.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Resume.status": %w`, err)}
		}
	}
	if len(rc.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Resume.owner"`)}
	}
	return nil
}

func (rc *ResumeCreate) sqlSave(ctx context.Context) (*Resume, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *ResumeCreate) createSpec() (*Resume, *sqlgraph.CreateSpec) {
	var (
		_node = &Resume{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(resume.Table, sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.Name(); ok {
		_spec.SetField(resume.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(resume.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.SetField(resume.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := rc.mutation.Shared(); ok {
		_spec.SetField(resume.FieldShared, field.TypeBool, value)
		_node.Shared = value
	}
	if value, ok := rc.mutation.ShareCode(); ok {
		_spec.SetField(resume.FieldShareCode, field.TypeString, value)
		_node.ShareCode = value
	}
	if value, ok := rc.mutation.Status(); ok {
		_spec.SetField(resume.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := rc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resume.OwnerTable,
			Columns: []string{resume.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_resumes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.TemplateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resume.TemplateTable,
			Columns: []string{resume.TemplateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.template_resumes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.PersonalInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   resume.PersonalInfoTable,
			Columns: []string{resume.PersonalInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalinfo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.ExperiencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resume.ExperiencesTable,
			Columns: resume.ExperiencesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(experience.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.EducationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resume.EducationsTable,
			Columns: resume.EducationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(education.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resume.SkillsTable,
			Columns: resume.SkillsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resume.ProjectsTable,
			Columns: resume.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.CertificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   resume.CertificationsTable,
			Columns: resume.CertificationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certification.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResumeCreateBulk is the builder for creating many Resume entities in bulk.
type ResumeCreateBulk struct {
	config
	err      error
	builders []*ResumeCreate
}

// Save creates the Resume entities in the database.
func (rcb *ResumeCreateBulk) Save(ctx context.Context) ([]*Resume, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Resume, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResumeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ResumeCreateBulk) SaveX(ctx context.Context) []*Resume {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ResumeCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ResumeCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
